# Use a base image with JDK 17 (or another available version if necessary)
FROM openjdk:17-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file into the container
COPY target/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway.jar

# Start the application
CMD ["java", "-jar", "api-gateway.jar"]
