# Use a base image with the required runtime environment
# Use a base image with JDK
FROM pratikshahodade123/openjdk-17-jdk-slim

# Set the working directory inside the container
WORKDIR /app


# Copy the application JAR file
COPY target/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway.jar

# Start the application
CMD ["java", "-jar","api-service.jar"]



