name: Build api-gateway image

on: 
  push:
    paths:
      - hospital-management/api-gateway/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Perform google formatter check
        run: |
          cd hospital-management/api-gateway
          mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=cd hospital-management/api-gateway

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/api-gateway
          mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker images
        run: |
         cd hospital-management/patient-service
         mvn clean install docker:build -Dimage.registry=${{ secrets.CONTAINER_REGISTRY_URL }} -Dimage.tag=$GITHUB_REF_NAME


      - name: Re-tag the docker image
        run: docker tag dnyanyog.org/api-gateway:latest ${{secrets.DOCKER_REGISTRY_USER}}/api-gateway:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push docker images
        run: docker push ${{secrets.CONTAINER_REGISTRY_URL}}/api-gateway:$GITHUB_REF_NAME
