name: Build Case-Service image

on:
  push:
    paths:
      - hospital-management/case-service/**

      
jobs:
  build-and-push-case-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Perform google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
        working-directory: hospital-management/case-service

      - name: GitLeaks Scan
        run: |
          cd hospital-management/case-service
          docker pull pratikshahodade123/gitleaks
          docker run -v "$(pwd):/scan" pratikshahodade123/gitleaks

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker image
        run: |
          cd hospital-management/case-service
          mvn clean install docker:build -Dimage.registry=${{ secrets.DOCKER_REGISTRY_USER }} -Dimage.tag=${{ github.ref_name }}
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker Image
        run: 
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/case-service:${{ github.ref_name }}

      - name: License finder
        run: |
          cd hospital-management/case-service
          docker pull pratikshahodade123/license-finder
          docker run -v "$(pwd):/scan" pratikshahodade123/license-finder
        continue-on-error: true
 
         
         
