name: Build hospital-console image

on:
  push:
    paths:
      - hospital-management/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Perform Google Formatter Check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
        working-directory: hospital-management/hospital-console-fxml
        continue-on-error: true

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: ${{ secrets.OWASP_SCAN_ENABLED == 'true' }}
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build Code and Create Docker Image
        run: |
          cd hospital-management/hospital-console-fxml
          mvn clean install docker:build

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker Image
        run: |
          docker tag hospital-console:latest ${{ secrets.DOCKER_REGISTRY_USER }}/hospital-console:latest
          docker push ${{ secrets.DOCKER_REGISTRY_USER }}/hospital-console:latest
