name: Build patient-service image

on:
  push:
    paths:
      - hospital-management/patient-service/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Perform Google formatter check
        run: |
          cd hospital-management/patient-service
          mvn com.spotify.fmt:fmt-maven-plugin:format

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0

      - name: OSS Scan
        run: |
          cd hospital-management/patient-service
          mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/patient-service
          mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker images
        run: mvn clean install docker:build -Dimage.registry=${{secrets.CONTAINER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/patient-service:$GITHUB_REF_NAME
